version: 2
updates:
- package-ecosystem: npm
  directory: "/electron-static/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/Genshin-Impact-Wish-Simulator/"
  schedule:
    interval: weekly
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "cargo"
  directory: "/Genshin-Impact-Wish-Simulator/src-tauri/"
  schedule:
    interval: "weekly"