name: Build app

on:
 workflow_dispatch:
 workflow_call:
 push:
    branches:
      - main # default branch
    paths:
      - ./electron-static/*

jobs:
  frontend:
    uses: ./.github/workflows/page.yml
  app:
    needs: frontend
    strategy:
      matrix:
        os: [windows,ubuntu,macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ./electron-static/node_modules
          key: ${{ matrix.os }}-npm-app-cache
          restore-keys: |
            ${{ matrix.os }}-npm-app-cache
      - name: Install Dependencies
        run: |
         cd electron-static
         yarn install
      - name: Download Artifact
        uses: actions/download-artifact@v3
      - name: extract new
        if: ${{ runner.os }}!=windows
        run: |          
         7z x ./frontend -oelectron-static/ -y
      - name: extract new(Windows)
        if: ${{ runner.os }}==windows
        run: |          
         7z x .\frontend -oelectron-static/ -y
      - name: Build
        run: |
         cd electron-static
         yarn run build
      - name: Package all
        run: |
         cd electron-static
         7z a -tzip genish-impact-${{ matrix.os }}-x64.zip ./genish-impact-*
      - name: Upload (${{ matrix.os }})
        uses: actions/upload-artifact@v3
        with:
          name: genish-impact-${{ matrix.os }}
          path: electron-static/genish-impact-${{ matrix.os }}-x64.zip
