name: Docker

on:
 workflow_dispatch:
 pull_request:
    branches:
      - main # default branch
    paths:
      - Genshin-Impact-Wish-Simulator/src/**/**
 push:
    branches:
      - main # default branch
    paths:
      - Genshin-Impact-Wish-Simulator/src/**/**

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t maizig/ysdm:latest .
      - name: Push to DockerHub
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: maizig/ysdm:latest
