name: Pages

on:
 workflow_dispatch:
 workflow_call:
 pull_request:
    branches:
      - main # default branch
    paths:
      - Genshin-Impact-Wish-Simulator/src/**/**
 push:
    branches:
      - main # default branch
    paths:
      - Genshin-Impact-Wish-Simulator/src/**/**

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
      - name: Cache NPM dependencies
        uses: actions/cache@v4.0.2
        with:
          path: ./Genshin-Impact-Wish-Simulator/node_modules
          key: ${{ runner.OS }}-npm-frontend-cache
          restore-keys: |
            ${{ runner.OS }}-npm-frontend-cache
      - name: Install Dependencies
        run: |
         cd Genshin-Impact-Wish-Simulator
         yarn install
      - name: Build
        run: |
         cd Genshin-Impact-Wish-Simulator
         yarn run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Genshin-Impact-Wish-Simulator/.vercel/output/static
  updater:
    if: false
    name: Update static files
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set Git config
        run: |
         git config --global user.name github-actions[bot]
         git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.4
        with:
            name: frontend
      - name: Remove old
        run: |
         cd electron-static
         rm -rf static
      - name: Extract new
        run: |          
         7z x ./frontend.zip -oelectron-static/ -y
      - name: Create commit
        run: |
         git add electron-static/static/**/**
         git commit -m "Update static files"
      - name: Push commit
        run: |
         git push
